import type { Metadata } from "next";
import "@shared/styles/globals.scss"
import Header from "@widgets/Header/ui";
import Footer from "@widgets/Footer/ui";
import { ModalProvider } from "@shared/context/Modal";

export const metadata: Metadata = {
  title: "TusranKG",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        <ModalProvider>
        <Header/>
        <main>
        {children}
        </main>
        <Footer/>
        </ModalProvider>
      </body>
    </html>
  );
}
